### ISSUE TITLE
Bounding box of slider arrows should also act as slider button

### ISSUE THREAD

**Issue by cwillems** [openHPI/video-player#11]
Currently, the clickable slider area for dual stream consists of the two seperate arrow shapes and the video divider line. This is not very user friendly. I would excpect the bounding box of both slider arrows (combined!) to act as clickable slider area (see drawing).

![clickable_slider_area](https://user-images.githubusercontent.com/1996660/29558583-d2cccecc-872c-11e7-96b0-87bdcb133451.png)

**Comment by soldag** [comment]
Fixed in 9b262a7.
