### ISSUE TITLE
Broken styles in Firefox/IE 

### ISSUE THREAD

**Issue by HDinger** [openHPI/video-player#14]
This is caused because FF/IE do not fully support shadow doms. Thus the styling rules are not encapsulated.

One example is the time box: 
![bildschirmfoto_2017-08-22_um_00 45 34](https://user-images.githubusercontent.com/7457313/29670985-9f02a0ae-88e8-11e7-88fc-e3eb6f0a0a7d.png)

**Comment by soldag** [comment]
Fixed meanwhile.
