### ISSUE TITLE
Migrate away from bower

### ISSUE THREAD

**Issue by jonathanherdt** [openHPI/video-player#2]
Bower is dying[[1]](https://www.quora.com/Is-Bower-dying)[[2]](https://github.com/bower/bower/issues/2298)[[3]](https://www.reddit.com/r/webdev/comments/6c8kpu/bower_now_deprecated_suggested_to_use_yarn_or/) ([the latest blog entry is more than half a year old and does not discuss new bower features, whereas the latest feature-related blog entry is more than a year old](https://bower.io/blog/)). When using bower, I get the following message about it being deprecated:

```
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more.
```

We should explore alternatives for using bower like the ones mentioned in the message above.

**Comment by soldag** [comment]
Done with upgrading to Polymer 3.
