### ISSUE TITLE
Fix screen orientation in analytics-manager

### ISSUE THREAD

**Issue by cwillems** [openHPI/video-player#31]
The screen orientation property is not available for IE 11 on Windows 7 and older versions of Edge, which breaks the player. Implement feature detection or handle the property for those browser in a suitable way.

For now, a [hotfix](https://github.com/openHPI/videoplayer/commit/81fa9a26482bf37ee29f11602bb52c8b0a1b9d4d) has been applied to bypass the issue.

**Comment by sebastiankliem** [comment]
https://github.com/openHPI/videoplayer/commit/4fded26388a0b6ebd6a004ef6f24633f2810aac7 fixes this. Tested manually on MacOS with Chrome 61, Firefox 55, Safari 10.1.2 and on BrowserStack with Edge 14
