### ISSUE TITLE
Analytics: Expose current slide number

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/video-player#35]
The analytics events include the following slide data at the moment:
```
currentSlide: {
  startPosition: 17,
  thumbnail: "/files/c4dc3d0f-8454-4b45-a602-1c6b04653c44/thumbnails/2100?format=jpg"
}
```

But the most important information is missing: `slide_number`

**Comment by sebastiankliem** [comment]
fixed by [#35_expose_slide_number](https://github.com/openHPI/videoplayer/tree/%2335_expose_slide_number) / https://github.com/openHPI/videoplayer/commit/1cc83b1b8c5028fd508f98e3aec2ce134ab6419c.
