### ISSUE TITLE
Update repo name to video-player

### ISSUE THREAD

**Issue by MrSerth** [openHPI/video-player#38]
In order to comply with the polymer specification and thus allow publishing a live demo to GitHub pages, the name of this repository needs to be updated to match the custom elements name.

Therefore, I request to change the repo name to `openHPI/video-player`. I will take care of the required name changes in the code (such as `package.json` with the corresponding links, etc.).

Afterwards, we might publish an interactive demo, such as I prepared with my fork:
https://mrserth.github.io/video-player/

**Comment by jprberlin** [comment]
Done.
