### ISSUE TITLE
Video-player does not collapse the space for interactive subtitles when they are disabled

### ISSUE THREAD

**Issue by tstaubitz** [openHPI/video-player#48]
Once I enable interactive subtitles, the video player keeps to reserve the space for them.
For all videos, if they have subtitles or not. The behaviour also does not change when the interactive subtitles are turned off again. 
Browsers: Definitely Safari, maybe others as well.
Steps to reproduce the behaviour:
1. go to a video in e.g. the imdb2017 openHPI course and show interactive subtitles
2. go to a video in e.g. the linux2018 openHPI course => where otherwise the interactive subtitles would be, there is a big black "hole"
3. go back to the imdb2017 video and hide the interactive subtitles
4. go back to the linux2018 video => the hole is still there

**Comment by soldag** [comment]
Fixed in ae26788.
