### ISSUE TITLE
Change State from Outside

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/video-player#50]
It would be nice if we could manipulate the video player state from outside, either by an api or events. There is research use case relying on it. ;)

Actions: play, pause, seek, subtitles, transcript, speed, quality, resizer, stream-layout etc.

**Comment by soldag** [comment]
I implemented an basic API, which is documented [here](https://github.com/openHPI/video-player/blob/dev/docs/api.md).
Manipulating the resizer is not yet possible, but will be added next.

**Comment by tobiasrohloff** [comment]
Nice!

**Comment by soldag** [comment]
Done
