### ISSUE TITLE
Player disfunctional in Opera Browser

### ISSUE THREAD

**Issue by cwillems** [openHPI/video-player#54]
In the current and previous version of Opera (Windows and OS X), the player doesn't work at all (not rendered).

Console shows a JavaScript errror:

```
Uncaught TypeError: Failed to construct 'HTMLElement': 
Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

**Comment by soldag** [comment]
This error occurs if you try to use the ES5 version of the player in a browser that supports ES6, which Opera does. To fix this you either need to use the ES6 version or include the [custom-elements-es5-adapterjs](https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs).
